out_dir: results
metric_best: mae
metric_agg: argmin
accelerator: "cuda:0"
tensorboard_each_run: True  # Log to Tensorboard each run
mlflow:
  use: False
  project: Exp
  name: pcqm4mv2-GRIT-RRWP
wandb:
  use: False
  project: pcqm4m
dataset:
  format: OGB
  name: PCQM4Mv2-full
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWPSE:
  enable: True
  ksteps: 16
  add_identity: True
  add_node_attr: False
  add_inverse: True
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_best: True
  ckpt_clean: True
#  ckpt_period: 100
model:
  type: GritTransformer
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: GritTransformer
  layers: 16
  n_heads: 8
  dim_hidden: 256 # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
  update_e: True
  attn:
    clamp: 5.
    act: 'relu'
    full_attn: True
    edge_enhance: True
    O_e: True
    norm_e: True
    signed_sqrt: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 256 # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0002
  max_epoch: 150
  scheduler: linear_with_warmup
  num_warmup_epochs: 10